version: '3'

services:
   appproxy:
     depends_on:
       - azbridge
     image: mafamafa/nginx-container-proxy:202503011815
     ports:
       - "80:8080"
     environment:
       DEFAULT_OVERRIDE_HOST: localhost
       DEFAULT_OVERRIDE_PORT: 80
       DEFAULT_OVERRIDE_PROTOCOL: http
       DEFAULT_OVERRIDE_IP: azbridge
       
   azbridge:
     image: mafamafa/azbridge:0.15
     environment:
       MYSQL_ROOT_PASSWORD: my_db_root_password
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: my_wordpress_db_password
